# Generated by Django 4.0.5 on 2023-04-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('goal_scored', models.IntegerField(blank=True, default=0)),
                ('goal_lost', models.IntegerField(blank=True, default=0)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='league', to='pentagoal.liga')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('home_team_score', models.IntegerField(blank=True, default=0)),
                ('away_team_score', models.IntegerField(blank=True, default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='pentagoal.teams')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='pentagoal.teams')),
                ('matches_league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_league', to='pentagoal.liga')),
            ],
        ),
    ]
